from enum import StrEnum


class Topology(StrEnum):
    UTS = "UTS"
    SYNCHRONOUS_MTS = "SYNCHRONOUS_MTS"
    ASYNCHRONOUS_MTS = "ASYNCHRONOUS_MTS"
    NATIVE_ND_ARRAY = "NATIVE_ND_ARRAY"


class TimestampOrigin(StrEnum):
    SOURCE_COLUMN = "SOURCE_COLUMN"
    MANIFEST_CONSTRUCTED = "MANIFEST_CONSTRUCTED"
    NONE = "NONE"


class ValidityShape(StrEnum):
    NONE = "NONE"
    ROW = "ROW"
    CELL = "CELL"
    PER_CHANNEL_RAGGED = "PER_CHANNEL_RAGGED"


class PhysicalLayout(StrEnum):
    ROW_MAJOR_CONTIG = "ROW_MAJOR_CONTIG"
    COLUMN_MAJOR_CONTIG = "COLUMN_MAJOR_CONTIG"
    STRIDED_VIEW = "STRIDED_VIEW"
    AOS_INTERLEAVED = "AOS_INTERLEAVED"
    SOA_COLUMNS = "SOA_COLUMNS"


class BenchmarkTrack(StrEnum):
    TIMESTAMP = "TIMESTAMP"
    VALUE = "VALUE"
    SYSTEM = "SYSTEM"


class ObjectLevel(StrEnum):
    P0_PRIMITIVE = "P0_PRIMITIVE"
    P1_STANDALONE_CODEC = "P1_STANDALONE_CODEC"
    P2_PIPELINE = "P2_PIPELINE"
    P3_STORAGE_SYSTEM = "P3_STORAGE_SYSTEM"


class ImplementationClass(StrEnum):
    CONVENTIONAL = "CONVENTIONAL"
    LEARNED = "LEARNED"
    HARDWARE_ACCELERATED = "HARDWARE_ACCELERATED"


class LossMode(StrEnum):
    LOSSLESS = "LOSSLESS"
    ERROR_BOUNDED_LOSSY = "ERROR_BOUNDED_LOSSY"
    RATE_CONTROLLED_LOSSY = "RATE_CONTROLLED_LOSSY"
    SUMMARY_ONLY = "SUMMARY_ONLY"


class ReconstructionMode(StrEnum):
    EXACT_GRID = "EXACT_GRID"
    APPROX_GRID = "APPROX_GRID"
    SPARSE_REPRESENTATION = "SPARSE_REPRESENTATION"
    SUMMARY_ONLY = "SUMMARY_ONLY"


class CapabilityStatus(StrEnum):
    DIRECT_SUPPORTED = "DIRECT_SUPPORTED"
    ADAPTER_LOSSLESS = "ADAPTER_LOSSLESS"
    ADAPTER_LOSSY = "ADAPTER_LOSSY"
    UNSUPPORTED = "UNSUPPORTED"


class RunStatus(StrEnum):
    PLANNED = "PLANNED"
    PASS = "PASS"
    UNSUPPORTED = "UNSUPPORTED"
    ADAPTER_LOSSY_ROUTED = "ADAPTER_LOSSY_ROUTED"
    ISA_UNSUPPORTED = "ISA_UNSUPPORTED"
    BUILD_UNAVAILABLE = "BUILD_UNAVAILABLE"
    SOURCE_INCOMPLETE = "SOURCE_INCOMPLETE"
    LICENSE_RESTRICTED = "LICENSE_RESTRICTED"
    HARNESS_CAPACITY_ERROR = "HARNESS_CAPACITY_ERROR"
    MEMORY_SAFETY_FAIL = "MEMORY_SAFETY_FAIL"
    RESOURCE_PRESSURE = "RESOURCE_PRESSURE"
    OVERSUBSCRIBED = "OVERSUBSCRIBED"
    CORRECTNESS_FAIL = "CORRECTNESS_FAIL"
    BOUND_VIOLATION = "BOUND_VIOLATION"
    OOM = "OOM"
    TIMEOUT = "TIMEOUT"
    INCOMPARABLE = "INCOMPARABLE"
    NONDETERMINISTIC = "NONDETERMINISTIC"
    CRASHED = "CRASHED"
    SCHEMA_ERROR = "SCHEMA_ERROR"


class ValueCouplingMode(StrEnum):
    COLUMN_INDEPENDENT = "COLUMN_INDEPENDENT"
    GROUPED_CHANNELS = "GROUPED_CHANNELS"
    FULL_MATRIX = "FULL_MATRIX"
    NATIVE_ND_ARRAY = "NATIVE_ND_ARRAY"


class PreprocessClass(StrEnum):
    NONE = "NONE"
    LOSSLESS_LAYOUT = "LOSSLESS_LAYOUT"
    LOSSLESS_SEMANTIC = "LOSSLESS_SEMANTIC"
    LOSSY_PREPROCESS = "LOSSY_PREPROCESS"
    TRAINING_LEARNED = "TRAINING_LEARNED"


class AdapterOperationKind(StrEnum):
    CONTIGUOUS_COPY = "CONTIGUOUS_COPY"
    TRANSPOSE_COPY = "TRANSPOSE_COPY"
    GATHER_SCATTER = "GATHER_SCATTER"
    ALIGNMENT_COPY = "ALIGNMENT_COPY"
    EXACT_WIDEN = "EXACT_WIDEN"
    ENDIANNESS_CONVERSION = "ENDIANNESS_CONVERSION"
    SAFE_OVERREAD_PADDING = "SAFE_OVERREAD_PADDING"
    NULL_MATERIALIZATION = "NULL_MATERIALIZATION"
    LOSSY_CAST = "LOSSY_CAST"
    DEVICE_STAGING = "DEVICE_STAGING"


class LicenseStatus(StrEnum):
    RUN_ALLOWED = "RUN_ALLOWED"
    REDISTRIBUTION_RESTRICTED = "REDISTRIBUTION_RESTRICTED"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
